ProyectoFinalAgenciaTours.WebApp/Controllers/DestinoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using ProyectoFinalAgenciaTours.Application.DTOs;
using ProyectoFinalAgenciaTours.Application.Exceptions;
using ProyectoFinalAgenciaTours.Application.Interfaces;
using ProyectoFinalAgenciaTours.Application.Services;
using ProyectoFinalAgenciaTours.WebApp.Models;

namespace ProyectoFinalAgenciaTours.WebApp.Controllers
{
    [Authorize]
    public class DestinoController : Controller
    {
        private readonly ILogger<DestinoController> _logger;
        private readonly IMapper _mapper;
        private readonly IDestinoService _destinoService;
        private readonly IPaisService _paisService;



        public DestinoController(
                ILogger<DestinoController> logger
            , IMapper mapper
            , IDestinoService destinoService
            , IPaisService paisService

            )
        {
            _logger = logger;
            _mapper = mapper;
            _destinoService = destinoService;
            _paisService = paisService;
        }

        public async Task<IActionResult> Index()
        {
            var _destino = await _destinoService.GetAllDestinoAsync();

            ViewData["Paises"] = new SelectList(await _paisService.GetAllPaisAsync(), "Id", "Nombre");

            return View(_destino);
        }

        [HttpGet]
        public IActionResult Add()
        {
            //return PartialView("_Add");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(int id, CreateDestinoDto createDestinoDto)
        {
            ViewData["Paises"] = new SelectList(await _paisService.GetAllPaisAsync(), "Id", "Nombre");

            if (!ModelState.IsValid)
            {
                return View("Add", createDestinoDto);
            }


            var estaAgregado = await _destinoService.AddDestinoAsync(createDestinoDto);
            if (estaAgregado is not null)
            {
                return RedirectToAction(nameof(Index));
            }
            

            return View("Add", createDestinoDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _destinoService.DeleteDestinoAsync(id);
            }
            catch (NotFoundException ex)
            {
                _logger.LogError(ex, "Error");
                ModelState.AddModelError(string.Empty, "Username o password no son válidos.");
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            catch (ApplicationException ex)
            {
                _logger.LogError(ex, "Error {Username}", ex.Message);
                ModelState.AddModelError(string.Empty, ex.Message);
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al Eliminar Registro {id}", id.ToString());

                ModelState.AddModelError("_addError", ex.Message);
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            SetSuccessToast("Eliminado correctamente", "bg-success");
            TempData["DisplayToast"] = true;

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var _destino = await _destinoService.GetDestinoByIdAsync(id);
            var updateDestino = _mapper.Map<UpdateDestinoDto>(_destino);
            
            ViewData["Paises"] = new SelectList(await _paisService.GetAllPaisAsync(), "Id", "Nombre");

            return View(updateDestino);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateDestinoDto updateDestinoDto)
        {

            if (!ModelState.IsValid)
            {
                return View("Update", updateDestinoDto);
            }

            await _destinoService.UpdateDestinoAsync(id, updateDestinoDto);

            return RedirectToAction(nameof(Index));
        }
        private void SetSuccessToast(string message, string cssClass)
        {

            TempData["TransactionsToast"] = JsonConvert.SerializeObject(new List<TransactionsToast>
            {
                new TransactionsToast
                {
                    Message = message,
                    CssClass = cssClass
                }
            });
        }
    }
}

ProyectoFinalAgenciaTours.WebApp/Controllers/PaisController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using ProyectoFinalAgenciaTours.Application.DTOs;
using ProyectoFinalAgenciaTours.Application.Exceptions;
using ProyectoFinalAgenciaTours.Application.Interfaces;
using ProyectoFinalAgenciaTours.WebApp.Models;

namespace ProyectoFinalAgenciaTours.WebApp.Controllers
{
    [Authorize]
    public class PaisController : Controller
    {
        private readonly ILogger<PaisController> _logger;
        private readonly IMapper _mapper;
        private readonly IPaisService _paisService;


        public PaisController(
                ILogger<PaisController> logger
            ,   IMapper mapper
            ,   IPaisService paisService
            )
        {
            _logger         = logger;
            _mapper         = mapper;
            _paisService    = paisService;
        }

        public async Task<IActionResult> Index()
        {
            var _pais = await _paisService.GetAllPaisAsync();
            return View(_pais);
        }

        public IActionResult Add()
        {
            //return PartialView("_Add");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(int id, CreatePaisDto createPaisDto)
        {

            if (!ModelState.IsValid)
            {
                return View("Add", createPaisDto);
            }

            var estaAgregado = await _paisService.AddPaisAsync(createPaisDto);
            if (estaAgregado is not null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View("Add", createPaisDto);
        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _paisService.DeletePaisAsync(id);
            }
            catch (NotFoundException ex)
            {
                _logger.LogError(ex, "Error");
                ModelState.AddModelError(string.Empty, "Username o password no son válidos.");
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            catch (ApplicationException ex)
            {
                _logger.LogError(ex, "Error {Username}", ex.Message);
                ModelState.AddModelError(string.Empty, ex.Message);
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al Eliminar Registro {id}", id.ToString());

                ModelState.AddModelError("_addError", ex.Message);
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            SetSuccessToast("Eliminado correctamente", "bg-success");
            TempData["DisplayToast"] = true;

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var _pais = await _paisService.GetPaisByIdAsync(id);
            var updateMateria = _mapper.Map<UpdatePaisDto>(_pais);

            return View(updateMateria);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdatePaisDto updatePaisDto)
        {

            if (!ModelState.IsValid)
            {
                return View("Update", updatePaisDto);
            }

            await _paisService.UpdatePaisAsync(id, updatePaisDto);

            return RedirectToAction(nameof(Index));
        }
        private void SetSuccessToast(string message, string cssClass)
        {

            TempData["TransactionsToast"] = JsonConvert.SerializeObject(new List<TransactionsToast>
            {
                new TransactionsToast
                {
                    Message = message,
                    CssClass = cssClass
                }
            });
        }

    }
}

ProyectoFinalAgenciaTours.WebApp/Controllers/TourController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using ProyectoFinalAgenciaTours.Application.DTOs;
using ProyectoFinalAgenciaTours.Application.Exceptions;
using ProyectoFinalAgenciaTours.Application.Interfaces;
using ProyectoFinalAgenciaTours.Application.Services;
using ProyectoFinalAgenciaTours.Domain.Entities;
using ProyectoFinalAgenciaTours.WebApp.Models;

namespace ProyectoFinalAgenciaTours.WebApp.Controllers
{
    [Authorize]
    public class TourController : Controller
    {

        private readonly ILogger<TourController> _logger;
        private readonly IMapper _mapper;
        private readonly ITourService _tourService;
        private readonly IPaisService _paisService;
        private readonly IDestinoService _destinoService;




        public TourController(
                ILogger<TourController> logger
            , IMapper mapper
            , ITourService tourService
            , IPaisService pasiService
            , IDestinoService destinoService



            )
        {
            _logger = logger;
            _mapper = mapper;
            _tourService = tourService;
            _paisService = pasiService;
            _destinoService = destinoService;
        }
        public async Task<IActionResult> Index()
        {

            var _destinos = await _destinoService.GetAllDestinoAsync();

            ViewData["Paises"] = new SelectList(await _paisService.GetAllPaisAsync(), "Id", "Nombre");
            ViewData["Destinos"] = new SelectList(
                _destinos.Select(p => new
                {
                    Id = p.Id,
                    NombreCompleto = $"{p.Nombre} ({p.Pais.Nombre})" 
                }).ToList(), 

                "Id",
                "NombreCompleto"
            );

            var _tour = await _tourService.GetAllTourAsync();

            return View(_tour);
        }


        [HttpPost]
        public async Task<IActionResult> Add(int id, CreateTourDto createTourDto)
        {

            var _paises     = await _paisService.GetAllPaisAsync();
            var _destinos   = await _destinoService.GetAllDestinoAsync();

            //ViewData["Paises"] = new SelectList( _paises, "Id", "Nombre");

            var paisesParaSelect = _destinos.Select(p => new 
            {
                Id = p.Id,
                Nombre = $"{p.Nombre} ({p.Pais.Nombre})"
            }).ToList();

            ViewData["Destinos"] = new SelectList( _destinos, "Id", "Nombre");

            if (!ModelState.IsValid)
            {
                return View("Add", createTourDto);
            }

            //var destinoElegido = await _destinoService.GetDestinoByIdAsync(createTourDto.DestinoId);
            //var createTourDtoCompleto = createTourDto with
            //{
            //    Destino = destinoElegido
            //};

            var estaAgregado = await _tourService.AddTourAsync(createTourDto);
            if (estaAgregado is not null)
            {
                return RedirectToAction(nameof(Index));
            }


            return View("Add", createTourDto);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var _pais = await _tourService.GetTourByIdAsync(id);
            var updateTour = _mapper.Map<UpdateTourDto>(_pais);

            var _destinos = await _destinoService.GetAllDestinoAsync();

            ViewData["Paises"] = new SelectList(await _paisService.GetAllPaisAsync(), "Id", "Nombre");
            ViewData["Destinos"] = new SelectList(
                _destinos.Select(p => new
                {
                    Id = p.Id,
                    NombreCompleto = $"{p.Nombre} ({p.Pais.Nombre})"
                }).ToList(),

                "Id",
                "NombreCompleto"
            );

            return View(updateTour);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateTourDto updateTourDto)
        {

            var _destinos = await _destinoService.GetAllDestinoAsync();

            ViewData["Paises"] = new SelectList(await _paisService.GetAllPaisAsync(), "Id", "Nombre");
            ViewData["Destinos"] = new SelectList(
                _destinos.Select(p => new
                {
                    Id = p.Id,
                    NombreCompleto = $"{p.Nombre} ({p.Pais.Nombre})"
                }).ToList(),

                "Id",
                "NombreCompleto"
            );

            if (!ModelState.IsValid)
            {
                return View("Update", updateTourDto);
            }

            await _tourService.UpdateTourAsync(id, updateTourDto);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _tourService.DeleteTourAsync(id);
            }
            catch (NotFoundException ex)
            {
                _logger.LogError(ex, "Error");
                ModelState.AddModelError(string.Empty, "Username o password no son válidos.");
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            catch (ApplicationException ex)
            {
                _logger.LogError(ex, "Error {Username}", ex.Message);
                ModelState.AddModelError(string.Empty, ex.Message);
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al Eliminar Registro {id}", id.ToString());

                ModelState.AddModelError("_addError", ex.Message);
                TempData["MateriaError"] = "El identificador no es válido.";
                return RedirectToAction(nameof(Index));
            }
            SetSuccessToast("Eliminado correctamente", "bg-success");
            TempData["DisplayToast"] = true;

            return RedirectToAction(nameof(Index));
        }

        private void SetSuccessToast(string message, string cssClass)
        {

            TempData["TransactionsToast"] = JsonConvert.SerializeObject(new List<TransactionsToast>
            {
                new TransactionsToast
                {
                    Message = message,
                    CssClass = cssClass
                }
            });
        }
    }
}

ProyectoFinalAgenciaTours.WebApp/Views/Shared/Sections/Menu/_HorizontalMenu.cshtml
@{
  TempData.Keep();
  string? currentPage =  ViewContext.HttpContext.Request.Path;
  ViewData["containerNav"] ??= "container-fluid";
}

<!-- Menu -->
<aside id="layout-menu" class="layout-menu-horizontal menu-horizontal  menu flex-grow-0">
    <div class='@ViewData["containerNav"] d-flex h-100'>
        @* ! Starter Kit menu-items *@
        <ul class="menu-inner">
            <li class='menu-item@(currentPage == "/" ? " active" : "")'>
                <a asp-controller="Home" asp-action="Index" class="menu-link">
                    <i class="menu-icon icon-base ri ri-home-smile-line"></i>
                    <div data-i18n="Inicio">Inicio</div>
                </a>
            </li>
            <li class='menu-item@((currentPage == "/Pais" | currentPage == "/pais") ? " active" : "")'>
                <a asp-controller="Pais" asp-action="Index" class="menu-link">
                    <i class="menu-icon icon-base ri ri-flag-line"></i>
                    <div data-i18n="Paises">Paises</div>
                </a>
            </li>
            <li class='menu-item@((currentPage == "/Destino" | currentPage == "/destino") ? " active" : "")'>
                <a asp-controller="Destino" asp-action="Index" class="menu-link">
                    <i class="menu-icon icon-base ri ri-map-pin-2-line"></i>
                    <div data-i18n="Destinos">Destinos</div>
                </a>
            </li>
            <li class='menu-item@((currentPage == "/Tour" | currentPage == "/tour") ? " active" : "")'>
                <a asp-controller="Tour" asp-action="Index" class="menu-link">
                    <i class="menu-icon icon-base ri ri-flight-takeoff-fill"></i>
                    <div data-i18n="Tours">Tours</div>
                </a>
            </li>
        </ul>
    </div>
</aside>
<!-- / Menu -->

ProyectoFinalAgenciaTours.WebApp/Views/Shared/Sections/Menu/_VerticalMenu.cshtml
@{
TempData.Keep();
string? currentPage = ViewContext.HttpContext.Request.Path;
}

<!-- Menu -->
@* ! Do this simple *@
<aside id="layout-menu" class="layout-menu menu-vertical menu">

  @* ! Hide app brand if navbar-full *@
  <div class='app-brand demo @((@ViewData["navbarFull"] != null && Convert.ToBoolean(@ViewData["navbarFull"])) ? "d-xl-none" : "")'>
    <a asp-controller="Home" asp-action="Index" class="app-brand-link">
      <span class="app-brand-logo demo">
        @await Html.PartialAsync("../_Partials/_Macros")
      </span>
      <span class="app-brand-text demo menu-text fw-semibold ms-2">@TempData.Peek("appName")</span>
    </a>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="M8.47365 11.7183C8.11707 12.0749 8.11707 12.6531 8.47365 13.0097L12.071 16.607C12.4615 16.9975 12.4615 17.6305 12.071 18.021C11.6805 18.4115 11.0475 18.4115 10.657 18.021L5.83009 13.1941C5.37164 12.7356 5.37164 11.9924 5.83009 11.5339L10.657 6.707C11.0475 6.31653 11.6805 6.31653 12.071 6.707C12.4615 7.09747 12.4615 7.73053 12.071 8.121L8.47365 11.7183Z" fill-opacity="0.9" />
        <path d="M14.3584 11.8336C14.0654 12.1266 14.0654 12.6014 14.3584 12.8944L18.071 16.607C18.4615 16.9975 18.4615 17.6305 18.071 18.021C17.6805 18.4115 17.0475 18.4115 16.657 18.021L11.6819 13.0459C11.3053 12.6693 11.3053 12.0587 11.6819 11.6821L16.657 6.707C17.0475 6.31653 17.6805 6.31653 18.071 6.707C18.4615 7.09747 18.4615 7.73053 18.071 8.121L14.3584 11.8336Z" fill-opacity="0.4" />
      </svg>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>

  @* ! Starter Kit menu-items *@
  <ul class="menu-inner py-1">
    <li class='menu-item@(currentPage == "/" ? " active" : "")'>
      <a asp-controller="Home" asp-action="Index" class="menu-link">
        <i class="menu-icon icon-base ri ri-home-smile-line"></i>
        <div data-i18n="Page 1">Page 1</div>
      </a>
    </li>
    <li class='menu-item@(currentPage == "/Page2" ? " active" : "")'>
      <a asp-controller="Page2" asp-action="Index" class="menu-link">
        <i class="menu-icon icon-base ri ri-file-3-line"></i>
        <div data-i18n="Page 2">Page 2</div>
      </a>
    </li>
  </ul>

</aside>
<!-- / Menu -->